export type Car = {
	car_id: number
	car_name: string
	ai_enabled: boolean
	allow_number_colors: boolean
	allow_number_font: boolean
	allow_sponsor_1: boolean
	allow_sponsor_2: boolean
	allow_wheel_color: boolean
	award_exempt: boolean
	car_dirpath: string
	car_name_abbreviated: string
	car_weight: number
	categories: string[]
	created: number
	first_sale: number
	forum_url: string
	free_with_subscription: boolean
	has_headlights: boolean
	has_multiple_dry_tire_types: boolean
	hp: number
	is_ps_purchasable: boolean
	max_power_adjust_pct: number
	max_weight_penalty_kg: number
	min_power_adjust_pct: number
	package_id: number
	patterns: number
	price: number
	price_display: string
	retired: boolean
	search_filters: string[]
	sku: number
	car_rules: Record<string, string>[]
	detail_copy: string
	detail_screen_shot_images: string[]
	detail_techspecs_copy: string
	folder: string
	gallery_prefix: string
	group_image: string
	group_name: string
	large_image: string
	logo: string
	small_image: string
	sponsor_logo: string
	template_path: string
	gallery_images: string
}

export const DefaultCar: Car = {
	car_id: 0,
	car_name: '',
	ai_enabled: false,
	allow_number_colors: false,
	allow_number_font: false,
	allow_sponsor_1: false,
	allow_sponsor_2: false,
	allow_wheel_color: false,
	award_exempt: false,
	car_dirpath: '',
	car_name_abbreviated: '',
	car_weight: 0,
	categories: [''],
	created: 0,
	first_sale: 0,
	forum_url: '',
	free_with_subscription: false,
	has_headlights: false,
	has_multiple_dry_tire_types: false,
	hp: 0,
	is_ps_purchasable: false,
	max_power_adjust_pct: 0,
	max_weight_penalty_kg: 0,
	min_power_adjust_pct: 0,
	package_id: 0,
	patterns: 0,
	price: 0,
	price_display: '',
	retired: false,
	search_filters: [''],
	sku: 0,
	car_rules: [{'': ''}],
	detail_copy: '',
	detail_screen_shot_images: [''],
	detail_techspecs_copy: '',
	folder: '',
	gallery_prefix: '',
	group_image: '',
	group_name: '',
	large_image: '',
	logo: '',
	small_image: '',
	sponsor_logo: '',
	template_path: '',
	gallery_images: '',
}
