export type Series = {
    id: number,
    name: string,
    logo: string,
    category_id: number,
    category: string,
    active: boolean,
    official: boolean,
    fixed_setup: boolean,
    min_license_level: number,
    forum_url: string,
    min_starters: number,
    max_starters: number,
    large_image: string,
    copy: string,
    small_image: string,
    sr_change: number,
    session_count: number,
    subsession_count: number,
    total_entry_count: number,
    track: string,
}

export const DefaultSeries: Series = {
    id: 0,
    name: '',
    logo: '',
    category_id: 0,
    category: '',
    active: false,
    official: false,
    fixed_setup: false,
    min_license_level: 0,
    forum_url: '',
    min_starters: 0,
    max_starters: 0,
    large_image: '',
    copy: '',
    small_image: '',
    sr_change: 0,
    session_count: 0,
    subsession_count: 0,
    total_entry_count: 0,
    track: '',
}
